apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-service-nodejs-rest
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: eks-service-nodejs-rest
  template:
    metadata:
      labels:
        app: eks-service-nodejs-rest
    spec:
      containers:
        - name: eks-service-nodejs-rest
          image: service-test-nodejs:latest
          ports:
            - containerPort: 3000
