apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-nodejs
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: service-nodejs
  template:
    metadata:
      labels:
        app: service-nodejs
    spec:
      containers:
        - name: service-nodejs-container
          image: josemanuel1999/service-test-nodejs:latest
          ports:
            - containerPort: 3000
