apiVersion: v1
kind: Service
metadata:
  name: eks-service-nodejs-rest
spec:
  selector:
    app: eks-service-nodejs-rest
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 3000 
  type: LoadBalancer 
